//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clubs
{
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    
    
    // CodeFluent Entities generated (http://www.softfluent.com). Date: Wednesday, 11 November 2015 01:11.
    // Build:1.0.61214.0829
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.61214.0829")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DataObjectAttribute()]
    [System.Diagnostics.DebuggerDisplayAttribute("Count={Count}")]
    [System.ComponentModel.TypeConverterAttribute(typeof(CodeFluent.Runtime.Design.CollectionTypeConverter))]
    public partial class CourtCollection : System.Collections.IList, System.Collections.ICollection, CodeFluent.Runtime.ICodeFluentSet, System.Collections.Generic.IList<Clubs.Court>, System.Collections.Generic.ICollection<Clubs.Court>, System.ComponentModel.IRaiseItemChangedEvents, System.ICloneable, System.ComponentModel.INotifyPropertyChanged, System.Collections.Specialized.INotifyCollectionChanged, System.ComponentModel.IBindingList, System.ComponentModel.ICancelAddNew
    {
        
        private bool _raisePropertyChangedEvents = true;
        
        private bool _raiseCollectionChangedEvents = true;
        
        [System.NonSerializedAttribute()]
        private System.Collections.Generic.List<Clubs.Court> _baseList = new System.Collections.Generic.List<Clubs.Court>();
        
        [System.NonSerializedAttribute()]
        private System.Collections.Generic.Dictionary<int, Clubs.Court> _baseTable = new System.Collections.Generic.Dictionary<int, Clubs.Court>();
        
        [System.NonSerializedAttribute()]
        private System.Collections.Hashtable _relations = new System.Collections.Hashtable();
        
        private int _maxCount = 2147483647;
        
        [System.NonSerializedAttribute()]
        private Clubs.Club _unspecifiedClubClub;
        
        [System.NonSerializedAttribute()]
        private Clubs.Facility _unspecifiedFacilityFacility;
        
        [System.NonSerializedAttribute()]
        private Clubs.Surface _unspecifiedSurfaceSurface;
        
        [System.NonSerializedAttribute()]
        private int _addNewPos = -1;
        
        [System.NonSerializedAttribute()]
        private CodeFluent.Runtime.Utilities.BindingListManager<Clubs.Court> _blm1204884029;
        
        private bool _raiseListChangedEvents = true;
        
        private System.Collections.Specialized.NotifyCollectionChangedEventHandler _h2943838991;

        event System.Collections.Specialized.NotifyCollectionChangedEventHandler System.Collections.Specialized.INotifyCollectionChanged.CollectionChanged{add{_h2943838991+=value;}remove{_h2943838991-=value;}}
        
        public CourtCollection()
        {
            this._blm1204884029 = new CodeFluent.Runtime.Utilities.BindingListManager<Clubs.Court>(this);
        }
        
        public CourtCollection(Clubs.Club unspecifiedClubClub, Clubs.Facility unspecifiedFacilityFacility, Clubs.Surface unspecifiedSurfaceSurface)
        {
            this._blm1204884029 = new CodeFluent.Runtime.Utilities.BindingListManager<Clubs.Court>(this);
            this._unspecifiedClubClub = unspecifiedClubClub;
            this._unspecifiedFacilityFacility = unspecifiedFacilityFacility;
            this._unspecifiedSurfaceSurface = unspecifiedSurfaceSurface;
        }
        
        [System.ComponentModel.BrowsableAttribute(false)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool RaisePropertyChangedEvents
        {
            get
            {
                return this._raisePropertyChangedEvents;
            }
            set
            {
                this._raisePropertyChangedEvents = value;
            }
        }
        
        public virtual bool RaiseCollectionChangedEvents
        {
            get
            {
                return this._raiseCollectionChangedEvents;
            }
            set
            {
                this._raiseCollectionChangedEvents = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        protected System.Collections.Generic.List<Clubs.Court> BaseList
        {
            get
            {
                return this._baseList;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        protected System.Collections.Generic.Dictionary<int, Clubs.Court> BaseTable
        {
            get
            {
                return this._baseTable;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        System.Collections.IDictionary CodeFluent.Runtime.ICodeFluentSet.Relations
        {
            get
            {
                return this._relations;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public virtual int MaxCount
        {
            get
            {
                return this._maxCount;
            }
            set
            {
                this._maxCount = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Clubs.Club UnspecifiedClubClub
        {
            get
            {
                return this._unspecifiedClubClub;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Clubs.Facility UnspecifiedFacilityFacility
        {
            get
            {
                return this._unspecifiedFacilityFacility;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Clubs.Surface UnspecifiedSurfaceSurface
        {
            get
            {
                return this._unspecifiedSurfaceSurface;
            }
        }
        
        public Clubs.Court this[int index]
        {
            get
            {
                return ((Clubs.Court)(this.BaseList[index]));
            }
            set
            {
                this.BaseList[index] = value;
            }
        }
        
        object System.Collections.IList.this[int index]
        {
            get
            {
                object i = this.BaseList[index];
                return i;
            }
            set
            {
                this.BaseList[index] = ((Clubs.Court)(value));
            }
        }
        
        public virtual int Count
        {
            get
            {
                int v = ((System.Collections.IList)(this.BaseList)).Count;
                return v;
            }
        }
        
        public virtual bool IsSynchronized
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsSynchronized;
                return v;
            }
        }
        
        public virtual object SyncRoot
        {
            get
            {
                object v = ((System.Collections.IList)(this.BaseList)).SyncRoot;
                return v;
            }
        }
        
        public virtual bool IsFixedSize
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsFixedSize;
                return v;
            }
        }
        
        public virtual bool IsReadOnly
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsReadOnly;
                return v;
            }
        }
        
        public virtual bool RaiseListChangedEvents
        {
            get
            {
                return this._raiseListChangedEvents;
            }
            set
            {
                this._raiseListChangedEvents = value;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowEdit
        {
            get
            {
                return this._blm1204884029.AllowEdit;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowNew
        {
            get
            {
                return this._blm1204884029.AllowNew;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowRemove
        {
            get
            {
                return this._blm1204884029.AllowRemove;
            }
        }
        
        bool System.ComponentModel.IBindingList.IsSorted
        {
            get
            {
                return this._blm1204884029.IsSorted;
            }
        }
        
        System.ComponentModel.ListSortDirection System.ComponentModel.IBindingList.SortDirection
        {
            get
            {
                return this._blm1204884029.SortDirection;
            }
        }
        
        System.ComponentModel.PropertyDescriptor System.ComponentModel.IBindingList.SortProperty
        {
            get
            {
                return this._blm1204884029.SortProperty;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsChangeNotification
        {
            get
            {
                return true;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsSearching
        {
            get
            {
                return this._blm1204884029.SupportsSearching;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsSorting
        {
            get
            {
                return this._blm1204884029.SupportsSorting;
            }
        }
        
        bool System.ComponentModel.IRaiseItemChangedEvents.RaisesItemChangedEvents
        {
            get
            {
                return this.RaiseListChangedEvents;
            }
        }
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.CollectionChangeEventHandler CollectionChanged;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.AddingNewEventHandler AddingNew;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.ListChangedEventHandler ListChanged;
        
        protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
        {
            if ((this.RaisePropertyChangedEvents == false))
            {
                return;
            }
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, e);
            }
        }
        
        protected virtual void OnCollectionChanged(System.ComponentModel.CollectionChangeEventArgs e)
        {
            if ((this.RaiseCollectionChangedEvents == false))
            {
                return;
            }
            if ((this.CollectionChanged != null))
            {
                this.CollectionChanged(this, e);
            }
            CodeFluent.Runtime.ServiceModel.CollectionChangeNotifier.Notify(this, e, this._h2943838991);
            this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Count"));
            this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Item[]"));
        }
        
        protected virtual void Relate(Clubs.Court item, CodeFluent.Runtime.CodeFluentRelationType relationType)
        {
            ((CodeFluent.Runtime.ICodeFluentSet)(this)).Relations[item] = relationType;
        }
        
        public int Add(Clubs.Court court)
        {
            int localAdd = this.BaseList.Count;
            this.BaseAdd(court);
            return localAdd;
        }
        
        protected virtual int BaseAdd(Clubs.Court court)
        {
            if ((court == null))
            {
                throw new System.ArgumentNullException("court");
            }
            if ((court.Id == -1))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "court", "Clubs.Court");
            }
            try
            {
                this.BaseTable.Add(court.Id, court);
            }
            catch (System.ArgumentNullException ane)
            {
                throw new System.ArgumentNullException(TennisClubLadder.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "Clubs.CourtCollection", court.EntityKey), ane);
            }
            catch (System.ArgumentException ae)
            {
                throw new System.ArgumentException(TennisClubLadder.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "Clubs.CourtCollection", court.Id), ae);
            }
            court.KeyChanged += new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<int>>(this.OnItemKeyChanged);
            int localAdd = this.BaseList.Count;
            this.BaseList.Add(court);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, court, localAdd));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, localAdd));
            return localAdd;
        }
        
        int System.Collections.IList.Add(object value)
        {
            Clubs.Court court = null;
            try
            {
                court = ((Clubs.Court)(value));
            }
            catch (System.InvalidCastException )
            {
                string key = null;
                try
                {
                    key = ((string)(value));
                    int count = this.Count;
                    if ((this.AddByEntityKey(key) != null))
                    {
                        return 1;
                    }
                    return 0;
                }
                catch (System.InvalidCastException )
                {
                }
                if ((key == null))
                {
                    throw new System.ArgumentException("value");
                }
            }
            if ((court == null))
            {
                throw new System.ArgumentException("value");
            }
            int localAdd = this.Add(court);
            return localAdd;
        }
        
        void System.Collections.Generic.ICollection<Clubs.Court>.Add(Clubs.Court court)
        {
            this.BaseAdd(court);
        }
        
        public virtual Clubs.Court AddByEntityKey(string key)
        {
            Clubs.Court court = Clubs.Court.LoadByEntityKey(key);
            if (((court != null) 
                        && (this.Contains(court) == false)))
            {
                this.Add(court);
            }
            return court;
        }
        
        public void Sort()
        {
            this.Sort(null);
        }
        
        public virtual void Sort(System.Collections.Generic.IComparer<Clubs.Court> comparer)
        {
            this.BaseList.Sort(comparer);
        }
        
        public void CopyTo(Clubs.Court[] array, int index)
        {
            this.BaseCopyTo(array, index);
        }
        
        protected virtual void BaseCopyTo(Clubs.Court[] array, int index)
        {
            this.BaseList.CopyTo(array, index);
        }
        
        void System.Collections.ICollection.CopyTo(System.Array array, int index)
        {
            CodeFluent.Runtime.Utilities.ConvertUtilities.CopyTo(this, array, index);
        }
        
        public bool Contains(Clubs.Court court)
        {
            bool localContains = this.BaseContains(court);
            return localContains;
        }
        
        protected virtual bool BaseContains(Clubs.Court court)
        {
            if ((court == null))
            {
                return false;
            }
            bool localContains = this.BaseTable.ContainsKey(court.Id);
            return localContains;
        }
        
        bool System.Collections.IList.Contains(object value)
        {
            Clubs.Court court;
			court = value as Clubs.Court;
            return this.Contains(court);
        }
        
        public int IndexOf(Clubs.Court court)
        {
            int localIndexOf = this.BaseIndexOf(court);
            return localIndexOf;
        }
        
        protected virtual int BaseIndexOf(Clubs.Court court)
        {
            if ((court == null))
            {
                return -1;
            }
            int localIndexOf = this.BaseList.IndexOf(court);
            return localIndexOf;
        }
        
        int System.Collections.IList.IndexOf(object value)
        {
            Clubs.Court court;
			court = value as Clubs.Court;
            return this.IndexOf(court);
        }
        
        public void Insert(int index, Clubs.Court court)
        {
            this.BaseInsert(index, court);
        }
        
        protected virtual void BaseInsert(int index, Clubs.Court court)
        {
            if ((court == null))
            {
                throw new System.ArgumentNullException("court");
            }
            try
            {
                this.BaseTable.Add(court.Id, court);
            }
            catch (System.ArgumentNullException ane)
            {
                throw new System.ArgumentNullException(TennisClubLadder.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "Clubs.CourtCollection", court.EntityKey), ane);
            }
            catch (System.ArgumentException ae)
            {
                throw new System.ArgumentException(TennisClubLadder.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "Clubs.CourtCollection", court.Id), ae);
            }
            this.BaseList.Insert(index, court);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, court, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, index));
        }
        
        void System.Collections.IList.Insert(int index, object value)
        {
            Clubs.Court court;
			court = value as Clubs.Court;
            this.Insert(index, court);
        }
        
        public virtual void Clear()
        {
            int index;
            int count = this.Count;
            for (index = 0; (index < count); index = (index + 1))
            {
                Clubs.Court Court = this[0];
                this.BaseRemove(Court);
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Refresh, null));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.Reset, -1));
        }
        
        public bool Remove(Clubs.Court court)
        {
            return this.BaseRemove(court);
        }
        
        protected virtual bool BaseRemove(Clubs.Court court)
        {
            if ((court == null))
            {
                throw new System.ArgumentNullException("court");
            }
            int index = this.IndexOf(court);
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(((System.ComponentModel.ListChangedType)(CodeFluent.Runtime.Utilities.SortableBindingList<Clubs.Court>.ListChangedTypeDeleting)), index));
            bool ret;
            ret = this.BaseList.Remove(court);
            court.KeyChanged -= new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<int>>(this.OnItemKeyChanged);
            ret = this.BaseTable.Remove(court.Id);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, court, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index));
            return ret;
        }
        
        void System.Collections.IList.Remove(object value)
        {
            Clubs.Court court;
			court = value as Clubs.Court;
            this.Remove(court);
        }
        
        public virtual void RemoveAt(int index)
        {
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(((System.ComponentModel.ListChangedType)(CodeFluent.Runtime.Utilities.SortableBindingList<Clubs.Court>.ListChangedTypeDeleting)), index));
            Clubs.Court court = this.BaseList[index];
            if ((court != null))
            {
                court.KeyChanged -= new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<int>>(this.OnItemKeyChanged);
                this.BaseTable.Remove(court.Id);
            }
            this.BaseList.RemoveAt(index);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, court, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index));
        }
        
        public virtual System.Collections.Generic.IEnumerator<Clubs.Court> GetEnumerator()
        {
            System.Collections.Generic.IEnumerator<Clubs.Court> e = this.BaseList.GetEnumerator();
            return e;
        }
        
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return this.BaseList.GetEnumerator();
        }
        
        private Clubs.Court TryGetValue(int key)
        {
            Clubs.Court court;
            if ((this.BaseTable.TryGetValue(key, out court) == true))
            {
                return court;
            }
            return null;
        }
        
        public void SetItem(int id, Clubs.Court value)
        {
            if ((id == -1))
            {
                throw new System.ArgumentNullException("id");
            }
            if ((value == null))
            {
                Clubs.Court court = this.TryGetValue(id);
                if ((court != null))
                {
                    this.Remove(court);
                }
                return;
            }
            this.BaseTable[value.Id] = value;
        }
        
        public Clubs.Court GetItem(int id)
        {
            if ((id == -1))
            {
                throw new System.ArgumentNullException("id");
            }
            Clubs.Court i = this.TryGetValue(id);
            return i;
        }
        
        public virtual void SaveAll()
        {
            int index;
            for (index = (this.Count - 1); (index >= 0); index = (index - 1))
            {
                Clubs.Court court = this[index];
                court.Save();
                if ((court.EntityState == CodeFluent.Runtime.CodeFluentEntityState.Deleted))
                {
                    this.Remove(court);
                }
            }
        }
        
        private void LoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            this._unspecifiedClubClub = null;
            this._unspecifiedFacilityFacility = null;
            this._unspecifiedSurfaceSurface = null;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    Clubs.Court court = new Clubs.Court();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(court)).ReadRecord(reader);
                    if ((this.BaseContains(court) == false))
                    {
                        this.BaseAdd(court);
                        count = (count + 1);
                    }
                    court.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Clubs.CourtCollection PageLoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            Clubs.CourtCollection ret = new Clubs.CourtCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = Clubs.CourtCollection.PageDataLoadAll(pageOptions);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadAll(pageIndex, pageSize, pageOptions, reader);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(TennisClubLadder.Constants.TennisClubLadderStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Clubs.CourtCollection LoadAll()
        {
            Clubs.CourtCollection ret = Clubs.CourtCollection.PageLoadAll(int.MinValue, int.MaxValue, null);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadAll(CodeFluent.Runtime.PageOptions pageOptions)
        {
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Court", "LoadAll");
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadAll()
        {
            System.Data.IDataReader reader = Clubs.CourtCollection.PageDataLoadAll(null);
            return reader;
        }
        
        private void LoadByClub(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader, Clubs.Club club)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            CodeFluent.Runtime.CodeFluentEntityState clubState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            if ((club != null))
            {
                clubState = club.EntityState;
            }
            this._unspecifiedClubClub = club;
            this._unspecifiedFacilityFacility = null;
            this._unspecifiedSurfaceSurface = null;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    Clubs.Court court = new Clubs.Court();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(court)).ReadRecord(reader);
                    if ((this.BaseContains(court) == false))
                    {
                        this.BaseAdd(court);
                        count = (count + 1);
                    }
                    court.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
            if ((club != null))
            {
                club.EntityState = clubState;
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Clubs.CourtCollection PageLoadByClub(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, Clubs.Club club)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            Clubs.CourtCollection ret = new Clubs.CourtCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = Clubs.CourtCollection.PageDataLoadByClub(pageOptions, club);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadByClub(pageIndex, pageSize, pageOptions, reader, club);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(TennisClubLadder.Constants.TennisClubLadderStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Clubs.CourtCollection LoadByClub(Clubs.Club club)
        {
            Clubs.CourtCollection ret = Clubs.CourtCollection.PageLoadByClub(int.MinValue, int.MaxValue, null, club);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadByClub(CodeFluent.Runtime.PageOptions pageOptions, Clubs.Club club)
        {
            if ((club == null))
            {
                return null;
            }
            if ((club.Id == -1))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "club", "Clubs.Club");
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Court", "LoadByClub");
            persistence.AddParameter("@ClubId", club.Id, ((int)(-1)));
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadByClub(Clubs.Club club)
        {
            System.Data.IDataReader reader = Clubs.CourtCollection.PageDataLoadByClub(null, club);
            return reader;
        }
        
        private void LoadByFacility(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader, Clubs.Facility facility)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            CodeFluent.Runtime.CodeFluentEntityState facilityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            if ((facility != null))
            {
                facilityState = facility.EntityState;
            }
            this._unspecifiedClubClub = null;
            this._unspecifiedFacilityFacility = facility;
            this._unspecifiedSurfaceSurface = null;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    Clubs.Court court = new Clubs.Court();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(court)).ReadRecord(reader);
                    if ((this.BaseContains(court) == false))
                    {
                        this.BaseAdd(court);
                        count = (count + 1);
                    }
                    court.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
            if ((facility != null))
            {
                facility.EntityState = facilityState;
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Clubs.CourtCollection PageLoadByFacility(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, Clubs.Facility facility)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            Clubs.CourtCollection ret = new Clubs.CourtCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = Clubs.CourtCollection.PageDataLoadByFacility(pageOptions, facility);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadByFacility(pageIndex, pageSize, pageOptions, reader, facility);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(TennisClubLadder.Constants.TennisClubLadderStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Clubs.CourtCollection LoadByFacility(Clubs.Facility facility)
        {
            Clubs.CourtCollection ret = Clubs.CourtCollection.PageLoadByFacility(int.MinValue, int.MaxValue, null, facility);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadByFacility(CodeFluent.Runtime.PageOptions pageOptions, Clubs.Facility facility)
        {
            if ((facility == null))
            {
                return null;
            }
            if ((facility.Id == -1))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "facility", "Clubs.Facility");
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Court", "LoadByFacility");
            persistence.AddParameter("@FacilityId", facility.Id, ((int)(-1)));
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadByFacility(Clubs.Facility facility)
        {
            System.Data.IDataReader reader = Clubs.CourtCollection.PageDataLoadByFacility(null, facility);
            return reader;
        }
        
        private void LoadBySurface(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader, Clubs.Surface surface)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            CodeFluent.Runtime.CodeFluentEntityState surfaceState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            if ((surface != null))
            {
                surfaceState = surface.EntityState;
            }
            this._unspecifiedClubClub = null;
            this._unspecifiedFacilityFacility = null;
            this._unspecifiedSurfaceSurface = surface;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    Clubs.Court court = new Clubs.Court();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(court)).ReadRecord(reader);
                    if ((this.BaseContains(court) == false))
                    {
                        this.BaseAdd(court);
                        count = (count + 1);
                    }
                    court.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
            if ((surface != null))
            {
                surface.EntityState = surfaceState;
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Clubs.CourtCollection PageLoadBySurface(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, Clubs.Surface surface)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            Clubs.CourtCollection ret = new Clubs.CourtCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = Clubs.CourtCollection.PageDataLoadBySurface(pageOptions, surface);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadBySurface(pageIndex, pageSize, pageOptions, reader, surface);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(TennisClubLadder.Constants.TennisClubLadderStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Clubs.CourtCollection LoadBySurface(Clubs.Surface surface)
        {
            Clubs.CourtCollection ret = Clubs.CourtCollection.PageLoadBySurface(int.MinValue, int.MaxValue, null, surface);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadBySurface(CodeFluent.Runtime.PageOptions pageOptions, Clubs.Surface surface)
        {
            if ((surface == null))
            {
                return null;
            }
            if ((surface.Id == -1))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "surface", "Clubs.Surface");
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Court", "LoadBySurface");
            persistence.AddParameter("@SurfaceId", surface.Id, ((int)(-1)));
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadBySurface(Clubs.Surface surface)
        {
            System.Data.IDataReader reader = Clubs.CourtCollection.PageDataLoadBySurface(null, surface);
            return reader;
        }
        
        protected virtual void BaseTrace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            writer.Write("[");
            writer.Write(string.Concat("Count=", this.Count));
            writer.Write("]");
        }
        
        public string Trace()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            System.IO.StringWriter stringWriter = new System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture);
            System.CodeDom.Compiler.IndentedTextWriter writer = new System.CodeDom.Compiler.IndentedTextWriter(stringWriter);
            this.BaseTrace(writer);
            writer.Flush();
            ((System.IDisposable)(writer)).Dispose();
            ((System.IDisposable)(stringWriter)).Dispose();
            string sr = stringBuilder.ToString();
            return sr;
        }
        
        void CodeFluent.Runtime.ICodeFluentObject.Trace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            this.BaseTrace(writer);
        }
        
        public virtual void CopyTo(Clubs.CourtCollection collection, bool deep)
        {
            if ((typeof(System.ICloneable).IsAssignableFrom(typeof(Clubs.Court)) == false))
            {
                deep = false;
            }
            System.Collections.Generic.IEnumerator<Clubs.Court> enumerator = this.GetEnumerator();
            bool b;
            for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
            {
                if ((deep == true))
                {
                    collection.Add(((Clubs.Court)(((System.ICloneable)(enumerator.Current)).Clone())));
                }
                else
                {
                    collection.Add(enumerator.Current);
                }
            }
        }
        
        public virtual Clubs.CourtCollection Clone(bool deep)
        {
            Clubs.CourtCollection ret = new Clubs.CourtCollection();
            this.CopyTo(ret, deep);
            return ret;
        }
        
        object System.ICloneable.Clone()
        {
            return this.Clone(true);
        }
        
        public virtual void CancelNew(int index)
        {
            if (((this._addNewPos >= 0) 
                        && (this._addNewPos == index)))
            {
                this.RemoveAt(index);
                this._addNewPos = -1;
            }
        }
        
        public virtual void EndNew(int index)
        {
            if (((this._addNewPos >= 0) 
                        && (this._addNewPos == index)))
            {
                this._addNewPos = -1;
            }
        }
        
        void System.ComponentModel.IBindingList.AddIndex(System.ComponentModel.PropertyDescriptor property)
        {
            this._blm1204884029.AddIndex(property);
        }
        
        protected virtual void OnAddingNew(System.ComponentModel.AddingNewEventArgs e)
        {
            if ((this.AddingNew != null))
            {
                this.AddingNew(this, e);
            }
        }
        
        object System.ComponentModel.IBindingList.AddNew()
        {
            Clubs.Court add = new Clubs.Court();
            System.ComponentModel.AddingNewEventArgs e = new System.ComponentModel.AddingNewEventArgs(add);
            this.OnAddingNew(e);
            add = ((Clubs.Court)(e.NewObject));
            if ((add == null))
            {
                add = new Clubs.Court();
            }
            add.Id = 0;
            this._addNewPos = this.Add(add);
            return add;
        }
        
        void System.ComponentModel.IBindingList.ApplySort(System.ComponentModel.PropertyDescriptor property, System.ComponentModel.ListSortDirection direction)
        {
            this._blm1204884029.ApplySort(property, direction);
        }
        
        int System.ComponentModel.IBindingList.Find(System.ComponentModel.PropertyDescriptor property, object key)
        {
            return this._blm1204884029.Find(property, key);
        }
        
        void System.ComponentModel.IBindingList.RemoveIndex(System.ComponentModel.PropertyDescriptor property)
        {
            this._blm1204884029.RemoveIndex(property);
        }
        
        void System.ComponentModel.IBindingList.RemoveSort()
        {
            this._blm1204884029.RemoveSort();
        }
        
        protected virtual void OnListChanged(System.ComponentModel.ListChangedEventArgs e)
        {
            if ((e == null))
            {
                throw new System.ArgumentNullException("e");
            }
            if ((this.RaiseListChangedEvents == false))
            {
                return;
            }
            if ((((e.ListChangedType == System.ComponentModel.ListChangedType.Reset) 
                        == false) 
                        && (e.NewIndex < 0)))
            {
                return;
            }
            if ((this.ListChanged != null))
            {
                this.ListChanged(this, e);
            }
        }
        
        public void AddRange(System.Collections.Generic.IEnumerable<Clubs.Court> collection)
        {
            CodeFluent.Runtime.Utilities.ConvertUtilities.AddRange(this, collection);
        }
        
        private void OnItemKeyChanged(object sender, CodeFluent.Runtime.Utilities.KeyChangedEventArgs<int> e)
        {
            if ((e == null))
            {
                throw new System.ArgumentNullException("e");
            }
            Clubs.Court existing;
            if ((this.BaseTable.TryGetValue(e.OldKey, out existing) == false))
            {
                return;
            }
            if (((sender != null) 
                        && (typeof(CodeFluent.Runtime.Utilities.IKeyable<int>).IsAssignableFrom(sender.GetType()) == true)))
            {
                CodeFluent.Runtime.Utilities.IKeyable<int> item = ((CodeFluent.Runtime.Utilities.IKeyable<int>)(sender));
                try
                {
                    this.BaseTable.Add(item.Key, existing);
                }
                catch (System.ArgumentNullException ane)
                {
                    throw new System.ArgumentNullException(TennisClubLadder.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "Clubs.CourtCollection", ((CodeFluent.Runtime.ICodeFluentEntity)(item)).EntityKey), ane);
                }
                catch (System.ArgumentException ae)
                {
                    throw new System.ArgumentException(TennisClubLadder.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "Clubs.CourtCollection", item.Key), ae);
                }
                this.BaseTable.Remove(e.OldKey);
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Clubs.CourtCollection PageLoadAll(int pageIndex, int pageSize)
        {
            return Clubs.CourtCollection.PageLoadAll(pageIndex, pageSize, null);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Clubs.CourtCollection PageLoadByClub(int pageIndex, int pageSize, int clubId)
        {
            Clubs.Club club = Clubs.Club.Load(clubId);
            if ((club == null))
            {
                return new Clubs.CourtCollection();
            }
            return Clubs.CourtCollection.PageLoadByClub(pageIndex, pageSize, null, club);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Clubs.CourtCollection PageLoadByFacility(int pageIndex, int pageSize, int facilityId)
        {
            Clubs.Facility facility = Clubs.Facility.Load(facilityId);
            if ((facility == null))
            {
                return new Clubs.CourtCollection();
            }
            return Clubs.CourtCollection.PageLoadByFacility(pageIndex, pageSize, null, facility);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Clubs.CourtCollection PageLoadBySurface(int pageIndex, int pageSize, int surfaceId)
        {
            Clubs.Surface surface = Clubs.Surface.Load(surfaceId);
            if ((surface == null))
            {
                return new Clubs.CourtCollection();
            }
            return Clubs.CourtCollection.PageLoadBySurface(pageIndex, pageSize, null, surface);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)]
        public static bool Save(Clubs.Court court)
        {
            if ((court == null))
            {
                return false;
            }
            bool ret = court.Save();
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)]
        public static bool Insert(Clubs.Court court)
        {
            bool ret = Clubs.Court.Save(court);
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)]
        public static bool Delete(Clubs.Court court)
        {
            if ((court == null))
            {
                return false;
            }
            bool ret = court.Delete();
            return ret;
        }
    }
}
