//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clubs
{
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    
    
    // CodeFluent Entities generated (http://www.softfluent.com). Date: Wednesday, 11 November 2015 01:11.
    // Build:1.0.61214.0829
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.61214.0829")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DataObjectAttribute()]
    [System.Diagnostics.DebuggerDisplayAttribute("EK={EntityKey}, Colour={Colour}, Id={Id}")]
    [System.ComponentModel.TypeConverterAttribute(typeof(CodeFluent.Runtime.Design.NameTypeConverter))]
    public partial class Court : System.ICloneable, System.IComparable, System.IComparable<Clubs.Court>, CodeFluent.Runtime.ICodeFluentCollectionEntity<int>, System.ComponentModel.IDataErrorInfo, CodeFluent.Runtime.ICodeFluentMemberValidator, CodeFluent.Runtime.ICodeFluentSummaryValidator, System.IEquatable<Clubs.Court>
    {
        
        private bool _raisePropertyChangedEvents = true;
        
        private CodeFluent.Runtime.CodeFluentEntityState _entityState;
        
        private byte[] _rowVersion;
        
        private int _id = -1;
        
        private string _colour = default(string);
        
        private System.Nullable<bool> _isActive = null;
        
        private System.Nullable<bool> _isOnline = null;
        
        private string _name = default(string);
        
        private string _referenceNo = default(string);
        
        private int _sequence = CodeFluentPersistence.DefaultInt32Value;
        
        private string _text = default(string);
        
        private string _title = default(string);
        
        private int _clubId = -1;
        
        [System.NonSerializedAttribute()]
        private Clubs.Club _club = null;
        
        private int _facilityId = -1;
        
        [System.NonSerializedAttribute()]
        private Clubs.Facility _facility = null;
        
        private int _surfaceId = -1;
        
        [System.NonSerializedAttribute()]
        private Clubs.Surface _surface = null;
        
        public Court()
        {
            this._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created;
        }
        
        [System.ComponentModel.BrowsableAttribute(false)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool RaisePropertyChangedEvents
        {
            get
            {
                return this._raisePropertyChangedEvents;
            }
            set
            {
                this._raisePropertyChangedEvents = value;
            }
        }
        
        public virtual string EntityKey
        {
            get
            {
                return this.Id.ToString();
            }
            set
            {
                this.Id = ((int)(ConvertUtilities.ChangeType(value, typeof(int), -1)));
            }
        }
        
        public virtual string EntityDisplayName
        {
            get
            {
                return this.Colour;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [System.ComponentModel.DataObjectFieldAttribute(false, true)]
        [System.ComponentModel.TypeConverterAttribute(typeof(CodeFluent.Runtime.Design.ByteArrayConverter))]
        public byte[] RowVersion
        {
            get
            {
                return this._rowVersion;
            }
            set
            {
                if (((value != null) 
                            && (value.Length == 0)))
                {
                    value = null;
                }
                this._rowVersion = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("RowVersion"));
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(((int)(-1)))]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false, Type=typeof(int))]
        [System.ComponentModel.DataObjectFieldAttribute(true)]
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((System.Collections.Generic.EqualityComparer<int>.Default.Equals(value, this._id) == true))
                {
                    return;
                }
                int oldKey = this._id;
                this._id = value;
                try
                {
                    this.OnCollectionKeyChanged(oldKey);
                }
                catch (System.ArgumentException )
                {
                    this._id = oldKey;
                    return;
                }
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Id"));
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(default(string))]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
        public string Colour
        {
            get
            {
                return this._colour;
            }
            set
            {
                this._colour = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Colour"));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> isActive
        {
            get
            {
                return this._isActive;
            }
            set
            {
                this._isActive = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("isActive"));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> isOnline
        {
            get
            {
                return this._isOnline;
            }
            set
            {
                this._isOnline = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("isOnline"));
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(default(string))]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Name"));
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(default(string))]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
        public string ReferenceNo
        {
            get
            {
                return this._referenceNo;
            }
            set
            {
                this._referenceNo = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("ReferenceNo"));
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false, Type=typeof(int))]
        public int Sequence
        {
            get
            {
                return this._sequence;
            }
            set
            {
                this._sequence = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Sequence"));
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(default(string))]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
        public string Text
        {
            get
            {
                return this._text;
            }
            set
            {
                this._text = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Text"));
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(default(string))]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
        public string Title
        {
            get
            {
                return this._title;
            }
            set
            {
                this._title = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Title"));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        [System.ComponentModel.DataObjectFieldAttribute(true)]
        public int ClubId
        {
            get
            {
                if (((this._clubId == -1) 
                            && (this._club != null)))
                {
                    this._clubId = this._club.Id;
                }
                return this._clubId;
            }
            set
            {
                if ((System.Collections.Generic.EqualityComparer<int>.Default.Equals(value, this.ClubId) == true))
                {
                    return;
                }
                this._club = null;
                this._clubId = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Club"));
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("ClubId"));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Clubs.Club Club
        {
            get
            {
                if ((this._club == null))
                {
                    this._club = Clubs.Club.Load(this._clubId);
                }
                return this._club;
            }
            set
            {
                this._clubId = -1;
                this._club = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Club"));
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("ClubId"));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        [System.ComponentModel.DataObjectFieldAttribute(true)]
        public int FacilityId
        {
            get
            {
                if (((this._facilityId == -1) 
                            && (this._facility != null)))
                {
                    this._facilityId = this._facility.Id;
                }
                return this._facilityId;
            }
            set
            {
                if ((System.Collections.Generic.EqualityComparer<int>.Default.Equals(value, this.FacilityId) == true))
                {
                    return;
                }
                this._facility = null;
                this._facilityId = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Facility"));
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("FacilityId"));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Clubs.Facility Facility
        {
            get
            {
                if ((this._facility == null))
                {
                    this._facility = Clubs.Facility.Load(this._facilityId);
                }
                return this._facility;
            }
            set
            {
                this._facilityId = -1;
                this._facility = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Facility"));
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("FacilityId"));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        [System.ComponentModel.DataObjectFieldAttribute(true)]
        public int SurfaceId
        {
            get
            {
                if (((this._surfaceId == -1) 
                            && (this._surface != null)))
                {
                    this._surfaceId = this._surface.Id;
                }
                return this._surfaceId;
            }
            set
            {
                if ((System.Collections.Generic.EqualityComparer<int>.Default.Equals(value, this.SurfaceId) == true))
                {
                    return;
                }
                this._surface = null;
                this._surfaceId = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Surface"));
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("SurfaceId"));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Clubs.Surface Surface
        {
            get
            {
                if ((this._surface == null))
                {
                    this._surface = Clubs.Surface.Load(this._surfaceId);
                }
                return this._surface;
            }
            set
            {
                this._surfaceId = -1;
                this._surface = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Surface"));
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("SurfaceId"));
            }
        }
        
        string System.ComponentModel.IDataErrorInfo.Error
        {
            get
            {
                return this.Validate(System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        string System.ComponentModel.IDataErrorInfo.this[string columnName]
        {
            get
            {
                return CodeFluentPersistence.ValidateMember(System.Globalization.CultureInfo.CurrentCulture, this, columnName, null);
            }
        }
        
        int CodeFluent.Runtime.Utilities.IKeyable<System.Int32>.Key
        {
            get
            {
                return this.Id;
            }
        }
        
        public virtual CodeFluent.Runtime.CodeFluentEntityState EntityState
        {
            get
            {
                return this._entityState;
            }
            set
            {
                if ((System.Collections.Generic.EqualityComparer<CodeFluent.Runtime.CodeFluentEntityState>.Default.Equals(value, this.EntityState) == true))
                {
                    return;
                }
                if (((this._entityState == CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted) 
                            && (value == CodeFluent.Runtime.CodeFluentEntityState.Modified)))
                {
                    return;
                }
                if (((this._entityState == CodeFluent.Runtime.CodeFluentEntityState.Created) 
                            && (value == CodeFluent.Runtime.CodeFluentEntityState.Modified)))
                {
                    return;
                }
                this._entityState = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("EntityState"));
            }
        }
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        [field:System.NonSerializedAttribute()]
        public event CodeFluent.Runtime.CodeFluentEntityActionEventHandler EntityAction;
        
        [field:System.NonSerializedAttribute()]
        public event System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<int>> KeyChanged;
        
        protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
        {
            if ((this.RaisePropertyChangedEvents == false))
            {
                return;
            }
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, e);
            }
        }
        
        protected virtual void OnEntityAction(CodeFluent.Runtime.CodeFluentEntityActionEventArgs e)
        {
            if ((this.EntityAction != null))
            {
                this.EntityAction(this, e);
            }
        }
        
        public virtual bool Equals(Clubs.Court court)
        {
            if ((court == null))
            {
                return false;
            }
            if ((this.Id == -1))
            {
                return base.Equals(court);
            }
            return (this.Id.Equals(court.Id) == true);
        }
        
        public override int GetHashCode()
        {
            return this._id;
        }
        
        public override bool Equals(object obj)
        {
            Clubs.Court court = null;
			court = obj as Clubs.Court;
            return this.Equals(court);
        }
        
        int System.IComparable.CompareTo(object value)
        {
            Clubs.Court court = null;
court = value as Clubs.Court;
            if ((court == null))
            {
                throw new System.ArgumentException("value");
            }
            int localCompareTo = this.CompareTo(court);
            return localCompareTo;
        }
        
        public virtual int CompareTo(Clubs.Court court)
        {
            if ((court == null))
            {
                throw new System.ArgumentNullException("court");
            }
            int localCompareTo = this.Id.CompareTo(court.Id);
            return localCompareTo;
        }
        
        public virtual string Validate(System.Globalization.CultureInfo culture)
        {
            return CodeFluentPersistence.Validate(culture, this, null);
        }
        
        public virtual void Validate(System.Globalization.CultureInfo culture, System.Collections.Generic.IList<CodeFluent.Runtime.CodeFluentValidationException> results)
        {
            CodeFluent.Runtime.CodeFluentEntityActionEventArgs evt = new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Validating, true, results);
            evt.Culture = culture;
            this.OnEntityAction(evt);
            if ((evt.Cancel == true))
            {
                string externalValidate;
                if ((evt.Argument != null))
                {
                    externalValidate = evt.Argument.ToString();
                }
                else
                {
                    externalValidate = TennisClubLadder.Resources.Manager.GetStringWithDefault(culture, "Clubs.Court.ExternalValidate", "Type \'Clubs.Court\' cannot be validated.", null);
                }
                CodeFluentPersistence.AddValidationError(results, externalValidate);
            }
            CodeFluentPersistence.ValidateMember(culture, results, this, null);
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Validated, false, results));
        }
        
        public void Validate()
        {
            string var = this.Validate(System.Globalization.CultureInfo.CurrentCulture);
            if ((var != null))
            {
                throw new CodeFluent.Runtime.CodeFluentValidationException(var);
            }
        }
        
        string CodeFluent.Runtime.ICodeFluentValidator.Validate(System.Globalization.CultureInfo culture)
        {
            string localValidate = this.Validate(culture);
            return localValidate;
        }
        
        void CodeFluent.Runtime.ICodeFluentMemberValidator.Validate(System.Globalization.CultureInfo culture, string memberName, System.Collections.Generic.IList<CodeFluent.Runtime.CodeFluentValidationException> results)
        {
            this.ValidateMember(culture, memberName, results);
        }
        
        public virtual bool Delete()
        {
            bool ret = false;
            CodeFluent.Runtime.CodeFluentEntityActionEventArgs evt = new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Deleting, true);
            this.OnEntityAction(evt);
            if ((evt.Cancel == true))
            {
                return ret;
            }
            if ((this.EntityState == CodeFluent.Runtime.CodeFluentEntityState.Deleted))
            {
                return ret;
            }
            if ((this.RowVersion == null))
            {
                return ret;
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Court", "Delete");
            persistence.AddParameter("@Court_Id", this.Id, ((int)(-1)));
            persistence.AddParameter("@_rowVersion", this.RowVersion);
            persistence.ExecuteNonQuery();
            this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted;
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Deleted, false, false));
            ret = true;
            return ret;
        }
        
        protected virtual void ReadRecord(System.Data.IDataReader reader, CodeFluent.Runtime.CodeFluentReloadOptions options)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((((options & CodeFluent.Runtime.CodeFluentReloadOptions.Properties) 
                        == 0) 
                        == false))
            {
                this._id = CodeFluentPersistence.GetReaderValue(reader, "Court_Id", ((int)(-1)));
                this._colour = CodeFluentPersistence.GetReaderValue(reader, "Court_Colour", ((string)(default(string))));
                this._isActive = CodeFluentPersistence.GetReaderValue<bool>(reader, "Court_isActive");
                this._isOnline = CodeFluentPersistence.GetReaderValue<bool>(reader, "Court_isOnline");
                this._name = CodeFluentPersistence.GetReaderValue(reader, "Court_Name", ((string)(default(string))));
                this._referenceNo = CodeFluentPersistence.GetReaderValue(reader, "Court_ReferenceNo", ((string)(default(string))));
                this._sequence = CodeFluentPersistence.GetReaderValue(reader, "Court_Sequence", ((int)(CodeFluentPersistence.DefaultInt32Value)));
                this._text = CodeFluentPersistence.GetReaderValue(reader, "Court_Text", ((string)(default(string))));
                this._title = CodeFluentPersistence.GetReaderValue(reader, "Court_Title", ((string)(default(string))));
                this.ClubId = CodeFluentPersistence.GetReaderValue(reader, "Court_Club_Id", ((int)(-1)));
                this.FacilityId = CodeFluentPersistence.GetReaderValue(reader, "Court_Facility_Id", ((int)(-1)));
                this.SurfaceId = CodeFluentPersistence.GetReaderValue(reader, "Court_Surface_Id", ((int)(-1)));
            }
            if ((((options & CodeFluent.Runtime.CodeFluentReloadOptions.RowVersion) 
                        == 0) 
                        == false))
            {
                this._rowVersion = CodeFluentPersistence.GetReaderValue(reader, "_rowVersion", ((byte[])(null)));
            }
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecord, false, false));
        }
        
        void CodeFluent.Runtime.ICodeFluentEntity.ReadRecord(System.Data.IDataReader reader)
        {
            this.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.Default);
        }
        
        protected virtual void ReadRecordOnSave(System.Data.IDataReader reader)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            this._id = CodeFluentPersistence.GetReaderValue(reader, "Court_Id", ((int)(-1)));
            this._rowVersion = CodeFluentPersistence.GetReaderValue(reader, "_rowVersion", ((byte[])(null)));
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecordOnSave, false, false));
        }
        
        void CodeFluent.Runtime.ICodeFluentEntity.ReadRecordOnSave(System.Data.IDataReader reader)
        {
            this.ReadRecordOnSave(reader);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Clubs.Court Load(int id)
        {
            if ((id == -1))
            {
                return null;
            }
            Clubs.Court court = new Clubs.Court();
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Court", "Load");
            persistence.AddParameter("@Id", id, ((int)(-1)));
            System.Data.IDataReader reader = null;
            try
            {
                reader = persistence.ExecuteReader();
                if ((reader.Read() == true))
                {
                    court.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.Default);
                    court.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                    return court;
                }
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                persistence.CompleteCommand();
            }
            return null;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, false)]
        public static Clubs.Court LoadById(int id)
        {
            if ((id == -1))
            {
                return null;
            }
            Clubs.Court court = new Clubs.Court();
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Court", "LoadById");
            persistence.AddParameter("@Id", id, ((int)(-1)));
            System.Data.IDataReader reader = null;
            try
            {
                reader = persistence.ExecuteReader();
                if ((reader.Read() == true))
                {
                    court.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.Default);
                    court.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                    return court;
                }
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                persistence.CompleteCommand();
            }
            return null;
        }
        
        public virtual bool Reload(CodeFluent.Runtime.CodeFluentReloadOptions options)
        {
            bool ret = false;
            if ((this.Id == -1))
            {
                return ret;
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Court", "Load");
            persistence.AddParameter("@Id", this.Id, ((int)(-1)));
            System.Data.IDataReader reader = null;
            try
            {
                reader = persistence.ExecuteReader();
                if ((reader.Read() == true))
                {
                    this.ReadRecord(reader, options);
                    this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                    ret = true;
                }
                else
                {
                    this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted;
                }
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                persistence.CompleteCommand();
            }
            return ret;
        }
        
        protected virtual bool BaseSave(bool force)
        {
            if ((this.EntityState == CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted))
            {
                this.Delete();
                return false;
            }
            CodeFluent.Runtime.CodeFluentEntityActionEventArgs evt = new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Saving, true);
            this.OnEntityAction(evt);
            if ((evt.Cancel == true))
            {
                return false;
            }
            CodeFluentPersistence.ThrowIfDeleted(this);
            this.Validate();
            if (((force == false) 
                        && (this.EntityState == CodeFluent.Runtime.CodeFluentEntityState.Unchanged)))
            {
                return false;
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Court", "Save");
            persistence.AddParameter("@Court_Id", this.Id, ((int)(-1)));
            persistence.AddParameter("@Court_Colour", this.Colour, default(string));
            persistence.AddParameter("@Court_isActive", this.isActive);
            persistence.AddParameter("@Court_isOnline", this.isOnline);
            persistence.AddParameter("@Court_Name", this.Name, default(string));
            persistence.AddParameter("@Court_ReferenceNo", this.ReferenceNo, default(string));
            persistence.AddParameter("@Court_Sequence", this.Sequence, CodeFluentPersistence.DefaultInt32Value);
            persistence.AddParameter("@Court_Text", this.Text, default(string));
            persistence.AddParameter("@Court_Title", this.Title, default(string));
            persistence.AddParameter("@Court_Club_Id", this.ClubId, ((int)(-1)));
            persistence.AddParameter("@Court_Facility_Id", this.FacilityId, ((int)(-1)));
            persistence.AddParameter("@Court_Surface_Id", this.SurfaceId, ((int)(-1)));
            persistence.AddParameter("@_trackLastWriteUser", persistence.Context.User.Name);
            persistence.AddParameter("@_rowVersion", this.RowVersion);
            System.Data.IDataReader reader = null;
            try
            {
                reader = persistence.ExecuteReader();
                if ((reader.Read() == true))
                {
                    this.ReadRecordOnSave(reader);
                }
                CodeFluentPersistence.NextResults(reader);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                persistence.CompleteCommand();
            }
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Saved, false, false));
            this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            return true;
        }
        
        public virtual bool Save()
        {
            bool localSave = this.BaseSave(false);
            return localSave;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)]
        public static bool Save(Clubs.Court court)
        {
            if ((court == null))
            {
                return false;
            }
            bool ret = court.Save();
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)]
        public static bool Insert(Clubs.Court court)
        {
            bool ret = Clubs.Court.Save(court);
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)]
        public static bool Delete(Clubs.Court court)
        {
            if ((court == null))
            {
                return false;
            }
            bool ret = court.Delete();
            return ret;
        }
        
        public string Trace()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            System.IO.StringWriter stringWriter = new System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture);
            System.CodeDom.Compiler.IndentedTextWriter writer = new System.CodeDom.Compiler.IndentedTextWriter(stringWriter);
            this.BaseTrace(writer);
            writer.Flush();
            ((System.IDisposable)(writer)).Dispose();
            ((System.IDisposable)(stringWriter)).Dispose();
            string sr = stringBuilder.ToString();
            return sr;
        }
        
        void CodeFluent.Runtime.ICodeFluentObject.Trace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            this.BaseTrace(writer);
        }
        
        protected virtual void BaseTrace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            writer.Write("[");
            writer.Write("Id=");
            writer.Write(this.Id);
            writer.Write(",");
            writer.Write("Colour=");
            writer.Write(this.Colour);
            writer.Write(",");
            writer.Write("isActive=");
            writer.Write(this.isActive);
            writer.Write(",");
            writer.Write("isOnline=");
            writer.Write(this.isOnline);
            writer.Write(",");
            writer.Write("Name=");
            writer.Write(this.Name);
            writer.Write(",");
            writer.Write("ReferenceNo=");
            writer.Write(this.ReferenceNo);
            writer.Write(",");
            writer.Write("Sequence=");
            writer.Write(this.Sequence);
            writer.Write(",");
            writer.Write("Text=");
            writer.Write(this.Text);
            writer.Write(",");
            writer.Write("Title=");
            writer.Write(this.Title);
            writer.Write(",");
            writer.Write("Club=");
            if ((this._club != null))
            {
                ((CodeFluent.Runtime.ICodeFluentObject)(this._club)).Trace(writer);
            }
            else
            {
                writer.Write("<null>");
            }
            writer.Write(",");
            writer.Write("_clubId=");
            writer.Write(this._clubId);
            writer.Write(",");
            writer.Write("Facility=");
            if ((this._facility != null))
            {
                ((CodeFluent.Runtime.ICodeFluentObject)(this._facility)).Trace(writer);
            }
            else
            {
                writer.Write("<null>");
            }
            writer.Write(",");
            writer.Write("_facilityId=");
            writer.Write(this._facilityId);
            writer.Write(",");
            writer.Write("Surface=");
            if ((this._surface != null))
            {
                ((CodeFluent.Runtime.ICodeFluentObject)(this._surface)).Trace(writer);
            }
            else
            {
                writer.Write("<null>");
            }
            writer.Write(",");
            writer.Write("_surfaceId=");
            writer.Write(this._surfaceId);
            writer.Write(", EntityState=");
            writer.Write(this.EntityState);
            writer.Write("]");
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Clubs.Court LoadByEntityKey(string key)
        {
            if ((key == string.Empty))
            {
                return null;
            }
            Clubs.Court court;
            int var = ((int)(ConvertUtilities.ChangeType(key, typeof(int), -1)));
            court = Clubs.Court.Load(var);
            return court;
        }
        
        protected virtual void ValidateMember(System.Globalization.CultureInfo culture, string memberName, System.Collections.Generic.IList<CodeFluent.Runtime.CodeFluentValidationException> results)
        {
        }
        
        public Clubs.Court Clone(bool deep)
        {
            Clubs.Court court = new Clubs.Court();
            this.CopyTo(court, deep);
            return court;
        }
        
        public Clubs.Court Clone()
        {
            Clubs.Court localClone = this.Clone(true);
            return localClone;
        }
        
        object System.ICloneable.Clone()
        {
            object localClone = this.Clone();
            return localClone;
        }
        
        public virtual void CopyFrom(System.Collections.IDictionary dict, bool deep)
        {
            if ((dict == null))
            {
                throw new System.ArgumentNullException("dict");
            }
            if ((dict.Contains("Id") == true))
            {
                this.Id = ((int)(ConvertUtilities.ChangeType(dict["Id"], typeof(int), -1)));
            }
            if ((dict.Contains("Sequence") == true))
            {
                this.Sequence = ((int)(ConvertUtilities.ChangeType(dict["Sequence"], typeof(int), CodeFluentPersistence.DefaultInt32Value)));
            }
            if ((dict.Contains("ReferenceNo") == true))
            {
                this.ReferenceNo = ((string)(ConvertUtilities.ChangeType(dict["ReferenceNo"], typeof(string), default(string))));
            }
            if ((dict.Contains("Title") == true))
            {
                this.Title = ((string)(ConvertUtilities.ChangeType(dict["Title"], typeof(string), default(string))));
            }
            if ((dict.Contains("Text") == true))
            {
                this.Text = ((string)(ConvertUtilities.ChangeType(dict["Text"], typeof(string), default(string))));
            }
            if ((dict.Contains("isActive") == true))
            {
                this.isActive = ((System.Nullable<System.Boolean>)(ConvertUtilities.ChangeType(dict["isActive"], typeof(System.Nullable<System.Boolean>), null)));
            }
            if ((dict.Contains("Colour") == true))
            {
                this.Colour = ((string)(ConvertUtilities.ChangeType(dict["Colour"], typeof(string), default(string))));
            }
            if ((dict.Contains("Name") == true))
            {
                this.Name = ((string)(ConvertUtilities.ChangeType(dict["Name"], typeof(string), default(string))));
            }
            if ((dict.Contains("isOnline") == true))
            {
                this.isOnline = ((System.Nullable<System.Boolean>)(ConvertUtilities.ChangeType(dict["isOnline"], typeof(System.Nullable<System.Boolean>), null)));
            }
            if ((dict.Contains("SurfaceId") == true))
            {
                this.SurfaceId = ((int)(ConvertUtilities.ChangeType(dict["SurfaceId"], typeof(int), -1)));
            }
            if ((dict.Contains("FacilityId") == true))
            {
                this.FacilityId = ((int)(ConvertUtilities.ChangeType(dict["FacilityId"], typeof(int), -1)));
            }
            if ((dict.Contains("ClubId") == true))
            {
                this.ClubId = ((int)(ConvertUtilities.ChangeType(dict["ClubId"], typeof(int), -1)));
            }
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.CopyFrom, false, dict));
        }
        
        public virtual void CopyTo(Clubs.Court court, bool deep)
        {
            if ((court == null))
            {
                throw new System.ArgumentNullException("court");
            }
            court.Id = this.Id;
            court.Sequence = this.Sequence;
            court.ReferenceNo = this.ReferenceNo;
            court.Title = this.Title;
            court.Text = this.Text;
            court.isActive = this.isActive;
            court.Colour = this.Colour;
            court.Name = this.Name;
            court.isOnline = this.isOnline;
            court.SurfaceId = this.SurfaceId;
            court.FacilityId = this.FacilityId;
            court.ClubId = this.ClubId;
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, court));
        }
        
        public virtual void CopyTo(System.Collections.IDictionary dict, bool deep)
        {
            if ((dict == null))
            {
                throw new System.ArgumentNullException("dict");
            }
            dict["Id"] = this.Id;
            dict["Sequence"] = this.Sequence;
            dict["ReferenceNo"] = this.ReferenceNo;
            dict["Title"] = this.Title;
            dict["Text"] = this.Text;
            dict["isActive"] = this.isActive;
            dict["Colour"] = this.Colour;
            dict["Name"] = this.Name;
            dict["isOnline"] = this.isOnline;
            dict["SurfaceId"] = this.SurfaceId;
            dict["FacilityId"] = this.FacilityId;
            dict["ClubId"] = this.ClubId;
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, dict));
        }
        
        protected void OnCollectionKeyChanged(int key)
        {
            if ((this.KeyChanged != null))
            {
                this.KeyChanged(this, new CodeFluent.Runtime.Utilities.KeyChangedEventArgs<int>(key));
            }
        }
    }
}
