//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ladders
{
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    
    
    // CodeFluent Entities generated (http://www.softfluent.com). Date: Wednesday, 11 November 2015 01:11.
    // Build:1.0.61214.0829
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.61214.0829")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DataObjectAttribute()]
    [System.Diagnostics.DebuggerDisplayAttribute("Count={Count}")]
    [System.ComponentModel.TypeConverterAttribute(typeof(CodeFluent.Runtime.Design.CollectionTypeConverter))]
    public partial class ChallengeCollection : System.Collections.IList, System.Collections.ICollection, CodeFluent.Runtime.ICodeFluentSet, System.Collections.Generic.IList<Ladders.Challenge>, System.Collections.Generic.ICollection<Ladders.Challenge>, System.ComponentModel.IRaiseItemChangedEvents, System.ICloneable, System.ComponentModel.INotifyPropertyChanged, System.Collections.Specialized.INotifyCollectionChanged, System.ComponentModel.IBindingList, System.ComponentModel.ICancelAddNew
    {
        
        private bool _raisePropertyChangedEvents = true;
        
        private bool _raiseCollectionChangedEvents = true;
        
        [System.NonSerializedAttribute()]
        private System.Collections.Generic.List<Ladders.Challenge> _baseList = new System.Collections.Generic.List<Ladders.Challenge>();
        
        [System.NonSerializedAttribute()]
        private System.Collections.Generic.Dictionary<int, Ladders.Challenge> _baseTable = new System.Collections.Generic.Dictionary<int, Ladders.Challenge>();
        
        [System.NonSerializedAttribute()]
        private System.Collections.Hashtable _relations = new System.Collections.Hashtable();
        
        private int _maxCount = 2147483647;
        
        [System.NonSerializedAttribute()]
        private Ladders.Ladder _challengesLadderLadder;
        
        [System.NonSerializedAttribute()]
        private Ladders.ChallengeStatus _unspecifiedChallengeStatusStatus;
        
        [System.NonSerializedAttribute()]
        private Clubs.Facility _unspecifiedFacilityFacility;
        
        [System.NonSerializedAttribute()]
        private Clubs.Court _unspecifiedCourtCourt;
        
        [System.NonSerializedAttribute()]
        private Ladders.MatchFormat _unspecifiedMatchFormatMatchFormat;
        
        [System.NonSerializedAttribute()]
        private int _addNewPos = -1;
        
        [System.NonSerializedAttribute()]
        private CodeFluent.Runtime.Utilities.BindingListManager<Ladders.Challenge> _blm2279252929;
        
        private bool _raiseListChangedEvents = true;
        
        private System.Collections.Specialized.NotifyCollectionChangedEventHandler _h2943838991;

        event System.Collections.Specialized.NotifyCollectionChangedEventHandler System.Collections.Specialized.INotifyCollectionChanged.CollectionChanged{add{_h2943838991+=value;}remove{_h2943838991-=value;}}
        
        public ChallengeCollection()
        {
            this._blm2279252929 = new CodeFluent.Runtime.Utilities.BindingListManager<Ladders.Challenge>(this);
        }
        
        public ChallengeCollection(Ladders.Ladder challengesLadderLadder, Ladders.ChallengeStatus unspecifiedChallengeStatusStatus, Clubs.Facility unspecifiedFacilityFacility, Clubs.Court unspecifiedCourtCourt, Ladders.MatchFormat unspecifiedMatchFormatMatchFormat)
        {
            this._blm2279252929 = new CodeFluent.Runtime.Utilities.BindingListManager<Ladders.Challenge>(this);
            this._challengesLadderLadder = challengesLadderLadder;
            this._unspecifiedChallengeStatusStatus = unspecifiedChallengeStatusStatus;
            this._unspecifiedFacilityFacility = unspecifiedFacilityFacility;
            this._unspecifiedCourtCourt = unspecifiedCourtCourt;
            this._unspecifiedMatchFormatMatchFormat = unspecifiedMatchFormatMatchFormat;
        }
        
        [System.ComponentModel.BrowsableAttribute(false)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool RaisePropertyChangedEvents
        {
            get
            {
                return this._raisePropertyChangedEvents;
            }
            set
            {
                this._raisePropertyChangedEvents = value;
            }
        }
        
        public virtual bool RaiseCollectionChangedEvents
        {
            get
            {
                return this._raiseCollectionChangedEvents;
            }
            set
            {
                this._raiseCollectionChangedEvents = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        protected System.Collections.Generic.List<Ladders.Challenge> BaseList
        {
            get
            {
                return this._baseList;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        protected System.Collections.Generic.Dictionary<int, Ladders.Challenge> BaseTable
        {
            get
            {
                return this._baseTable;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        System.Collections.IDictionary CodeFluent.Runtime.ICodeFluentSet.Relations
        {
            get
            {
                return this._relations;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public virtual int MaxCount
        {
            get
            {
                return this._maxCount;
            }
            set
            {
                this._maxCount = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Ladders.Ladder ChallengesLadderLadder
        {
            get
            {
                return this._challengesLadderLadder;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Ladders.ChallengeStatus UnspecifiedChallengeStatusStatus
        {
            get
            {
                return this._unspecifiedChallengeStatusStatus;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Clubs.Facility UnspecifiedFacilityFacility
        {
            get
            {
                return this._unspecifiedFacilityFacility;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Clubs.Court UnspecifiedCourtCourt
        {
            get
            {
                return this._unspecifiedCourtCourt;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Ladders.MatchFormat UnspecifiedMatchFormatMatchFormat
        {
            get
            {
                return this._unspecifiedMatchFormatMatchFormat;
            }
        }
        
        public Ladders.Challenge this[int index]
        {
            get
            {
                return ((Ladders.Challenge)(this.BaseList[index]));
            }
            set
            {
                this.BaseList[index] = value;
            }
        }
        
        object System.Collections.IList.this[int index]
        {
            get
            {
                object i = this.BaseList[index];
                return i;
            }
            set
            {
                this.BaseList[index] = ((Ladders.Challenge)(value));
            }
        }
        
        public virtual int Count
        {
            get
            {
                int v = ((System.Collections.IList)(this.BaseList)).Count;
                return v;
            }
        }
        
        public virtual bool IsSynchronized
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsSynchronized;
                return v;
            }
        }
        
        public virtual object SyncRoot
        {
            get
            {
                object v = ((System.Collections.IList)(this.BaseList)).SyncRoot;
                return v;
            }
        }
        
        public virtual bool IsFixedSize
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsFixedSize;
                return v;
            }
        }
        
        public virtual bool IsReadOnly
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsReadOnly;
                return v;
            }
        }
        
        public virtual bool RaiseListChangedEvents
        {
            get
            {
                return this._raiseListChangedEvents;
            }
            set
            {
                this._raiseListChangedEvents = value;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowEdit
        {
            get
            {
                return this._blm2279252929.AllowEdit;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowNew
        {
            get
            {
                return this._blm2279252929.AllowNew;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowRemove
        {
            get
            {
                return this._blm2279252929.AllowRemove;
            }
        }
        
        bool System.ComponentModel.IBindingList.IsSorted
        {
            get
            {
                return this._blm2279252929.IsSorted;
            }
        }
        
        System.ComponentModel.ListSortDirection System.ComponentModel.IBindingList.SortDirection
        {
            get
            {
                return this._blm2279252929.SortDirection;
            }
        }
        
        System.ComponentModel.PropertyDescriptor System.ComponentModel.IBindingList.SortProperty
        {
            get
            {
                return this._blm2279252929.SortProperty;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsChangeNotification
        {
            get
            {
                return true;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsSearching
        {
            get
            {
                return this._blm2279252929.SupportsSearching;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsSorting
        {
            get
            {
                return this._blm2279252929.SupportsSorting;
            }
        }
        
        bool System.ComponentModel.IRaiseItemChangedEvents.RaisesItemChangedEvents
        {
            get
            {
                return this.RaiseListChangedEvents;
            }
        }
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.CollectionChangeEventHandler CollectionChanged;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.AddingNewEventHandler AddingNew;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.ListChangedEventHandler ListChanged;
        
        protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
        {
            if ((this.RaisePropertyChangedEvents == false))
            {
                return;
            }
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, e);
            }
        }
        
        protected virtual void OnCollectionChanged(System.ComponentModel.CollectionChangeEventArgs e)
        {
            if ((this.RaiseCollectionChangedEvents == false))
            {
                return;
            }
            if ((this.CollectionChanged != null))
            {
                this.CollectionChanged(this, e);
            }
            CodeFluent.Runtime.ServiceModel.CollectionChangeNotifier.Notify(this, e, this._h2943838991);
            this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Count"));
            this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Item[]"));
        }
        
        protected virtual void Relate(Ladders.Challenge item, CodeFluent.Runtime.CodeFluentRelationType relationType)
        {
            ((CodeFluent.Runtime.ICodeFluentSet)(this)).Relations[item] = relationType;
        }
        
        public int Add(Ladders.Challenge challenge)
        {
            int localAdd = this.BaseList.Count;
            this.BaseAdd(challenge);
            return localAdd;
        }
        
        protected virtual int BaseAdd(Ladders.Challenge challenge)
        {
            if ((challenge == null))
            {
                throw new System.ArgumentNullException("challenge");
            }
            if ((challenge.Id == -1))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "challenge", "Ladders.Challenge");
            }
            try
            {
                this.BaseTable.Add(challenge.Id, challenge);
            }
            catch (System.ArgumentNullException ane)
            {
                throw new System.ArgumentNullException(TennisClubLadder.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "Ladders.ChallengeCollection", challenge.EntityKey), ane);
            }
            catch (System.ArgumentException ae)
            {
                throw new System.ArgumentException(TennisClubLadder.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "Ladders.ChallengeCollection", challenge.Id), ae);
            }
            challenge.KeyChanged += new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<int>>(this.OnItemKeyChanged);
            if ((this._challengesLadderLadder != null))
            {
                challenge.Ladder = this._challengesLadderLadder;
            }
            int localAdd = this.BaseList.Count;
            this.BaseList.Add(challenge);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, challenge, localAdd));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, localAdd));
            return localAdd;
        }
        
        int System.Collections.IList.Add(object value)
        {
            Ladders.Challenge challenge = null;
            try
            {
                challenge = ((Ladders.Challenge)(value));
            }
            catch (System.InvalidCastException )
            {
                string key = null;
                try
                {
                    key = ((string)(value));
                    int count = this.Count;
                    if ((this.AddByEntityKey(key) != null))
                    {
                        return 1;
                    }
                    return 0;
                }
                catch (System.InvalidCastException )
                {
                }
                if ((key == null))
                {
                    throw new System.ArgumentException("value");
                }
            }
            if ((challenge == null))
            {
                throw new System.ArgumentException("value");
            }
            int localAdd = this.Add(challenge);
            return localAdd;
        }
        
        void System.Collections.Generic.ICollection<Ladders.Challenge>.Add(Ladders.Challenge challenge)
        {
            this.BaseAdd(challenge);
        }
        
        public virtual Ladders.Challenge AddByEntityKey(string key)
        {
            Ladders.Challenge challenge = Ladders.Challenge.LoadByEntityKey(key);
            if (((challenge != null) 
                        && (this.Contains(challenge) == false)))
            {
                this.Add(challenge);
            }
            return challenge;
        }
        
        public void Sort()
        {
            this.Sort(null);
        }
        
        public virtual void Sort(System.Collections.Generic.IComparer<Ladders.Challenge> comparer)
        {
            this.BaseList.Sort(comparer);
        }
        
        public void CopyTo(Ladders.Challenge[] array, int index)
        {
            this.BaseCopyTo(array, index);
        }
        
        protected virtual void BaseCopyTo(Ladders.Challenge[] array, int index)
        {
            this.BaseList.CopyTo(array, index);
        }
        
        void System.Collections.ICollection.CopyTo(System.Array array, int index)
        {
            CodeFluent.Runtime.Utilities.ConvertUtilities.CopyTo(this, array, index);
        }
        
        public bool Contains(Ladders.Challenge challenge)
        {
            bool localContains = this.BaseContains(challenge);
            return localContains;
        }
        
        protected virtual bool BaseContains(Ladders.Challenge challenge)
        {
            if ((challenge == null))
            {
                return false;
            }
            bool localContains = this.BaseTable.ContainsKey(challenge.Id);
            return localContains;
        }
        
        bool System.Collections.IList.Contains(object value)
        {
            Ladders.Challenge challenge;
			challenge = value as Ladders.Challenge;
            return this.Contains(challenge);
        }
        
        public int IndexOf(Ladders.Challenge challenge)
        {
            int localIndexOf = this.BaseIndexOf(challenge);
            return localIndexOf;
        }
        
        protected virtual int BaseIndexOf(Ladders.Challenge challenge)
        {
            if ((challenge == null))
            {
                return -1;
            }
            int localIndexOf = this.BaseList.IndexOf(challenge);
            return localIndexOf;
        }
        
        int System.Collections.IList.IndexOf(object value)
        {
            Ladders.Challenge challenge;
			challenge = value as Ladders.Challenge;
            return this.IndexOf(challenge);
        }
        
        public void Insert(int index, Ladders.Challenge challenge)
        {
            this.BaseInsert(index, challenge);
        }
        
        protected virtual void BaseInsert(int index, Ladders.Challenge challenge)
        {
            if ((challenge == null))
            {
                throw new System.ArgumentNullException("challenge");
            }
            try
            {
                this.BaseTable.Add(challenge.Id, challenge);
            }
            catch (System.ArgumentNullException ane)
            {
                throw new System.ArgumentNullException(TennisClubLadder.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "Ladders.ChallengeCollection", challenge.EntityKey), ane);
            }
            catch (System.ArgumentException ae)
            {
                throw new System.ArgumentException(TennisClubLadder.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "Ladders.ChallengeCollection", challenge.Id), ae);
            }
            this.BaseList.Insert(index, challenge);
            if ((this._challengesLadderLadder != null))
            {
                challenge.Ladder = this._challengesLadderLadder;
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, challenge, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, index));
        }
        
        void System.Collections.IList.Insert(int index, object value)
        {
            Ladders.Challenge challenge;
			challenge = value as Ladders.Challenge;
            this.Insert(index, challenge);
        }
        
        public virtual void Clear()
        {
            int index;
            int count = this.Count;
            for (index = 0; (index < count); index = (index + 1))
            {
                Ladders.Challenge Challenge = this[0];
                this.BaseRemove(Challenge);
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Refresh, null));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.Reset, -1));
        }
        
        public bool Remove(Ladders.Challenge challenge)
        {
            return this.BaseRemove(challenge);
        }
        
        protected virtual bool BaseRemove(Ladders.Challenge challenge)
        {
            if ((challenge == null))
            {
                throw new System.ArgumentNullException("challenge");
            }
            int index = this.IndexOf(challenge);
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(((System.ComponentModel.ListChangedType)(CodeFluent.Runtime.Utilities.SortableBindingList<Ladders.Challenge>.ListChangedTypeDeleting)), index));
            bool ret;
            ret = this.BaseList.Remove(challenge);
            challenge.KeyChanged -= new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<int>>(this.OnItemKeyChanged);
            ret = this.BaseTable.Remove(challenge.Id);
            if ((this._challengesLadderLadder != null))
            {
                challenge.Ladder = null;
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, challenge, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index));
            return ret;
        }
        
        void System.Collections.IList.Remove(object value)
        {
            Ladders.Challenge challenge;
			challenge = value as Ladders.Challenge;
            this.Remove(challenge);
        }
        
        public virtual void RemoveAt(int index)
        {
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(((System.ComponentModel.ListChangedType)(CodeFluent.Runtime.Utilities.SortableBindingList<Ladders.Challenge>.ListChangedTypeDeleting)), index));
            Ladders.Challenge challenge = this.BaseList[index];
            if ((challenge != null))
            {
                challenge.KeyChanged -= new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<int>>(this.OnItemKeyChanged);
                this.BaseTable.Remove(challenge.Id);
            }
            if ((this._challengesLadderLadder != null))
            {
                challenge.Ladder = null;
            }
            this.BaseList.RemoveAt(index);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, challenge, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index));
        }
        
        public virtual System.Collections.Generic.IEnumerator<Ladders.Challenge> GetEnumerator()
        {
            System.Collections.Generic.IEnumerator<Ladders.Challenge> e = this.BaseList.GetEnumerator();
            return e;
        }
        
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return this.BaseList.GetEnumerator();
        }
        
        private Ladders.Challenge TryGetValue(int key)
        {
            Ladders.Challenge challenge;
            if ((this.BaseTable.TryGetValue(key, out challenge) == true))
            {
                return challenge;
            }
            return null;
        }
        
        public void SetItem(int id, Ladders.Challenge value)
        {
            if ((id == -1))
            {
                throw new System.ArgumentNullException("id");
            }
            if ((value == null))
            {
                Ladders.Challenge challenge = this.TryGetValue(id);
                if ((challenge != null))
                {
                    this.Remove(challenge);
                }
                return;
            }
            this.BaseTable[value.Id] = value;
        }
        
        public Ladders.Challenge GetItem(int id)
        {
            if ((id == -1))
            {
                throw new System.ArgumentNullException("id");
            }
            Ladders.Challenge i = this.TryGetValue(id);
            return i;
        }
        
        public virtual void SaveAll()
        {
            int index;
            for (index = (this.Count - 1); (index >= 0); index = (index - 1))
            {
                Ladders.Challenge challenge = this[index];
                challenge.Save();
                if ((challenge.EntityState == CodeFluent.Runtime.CodeFluentEntityState.Deleted))
                {
                    this.Remove(challenge);
                }
            }
        }
        
        private void LoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            this._challengesLadderLadder = null;
            this._unspecifiedChallengeStatusStatus = null;
            this._unspecifiedFacilityFacility = null;
            this._unspecifiedCourtCourt = null;
            this._unspecifiedMatchFormatMatchFormat = null;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    Ladders.Challenge challenge = new Ladders.Challenge();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(challenge)).ReadRecord(reader);
                    if ((this.BaseContains(challenge) == false))
                    {
                        this.BaseAdd(challenge);
                        count = (count + 1);
                    }
                    challenge.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Ladders.ChallengeCollection PageLoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            Ladders.ChallengeCollection ret = new Ladders.ChallengeCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = Ladders.ChallengeCollection.PageDataLoadAll(pageOptions);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadAll(pageIndex, pageSize, pageOptions, reader);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(TennisClubLadder.Constants.TennisClubLadderStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Ladders.ChallengeCollection LoadAll()
        {
            Ladders.ChallengeCollection ret = Ladders.ChallengeCollection.PageLoadAll(int.MinValue, int.MaxValue, null);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadAll(CodeFluent.Runtime.PageOptions pageOptions)
        {
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Challenge", "LoadAll");
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadAll()
        {
            System.Data.IDataReader reader = Ladders.ChallengeCollection.PageDataLoadAll(null);
            return reader;
        }
        
        private void LoadByLadder(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader, Ladders.Ladder ladder)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            CodeFluent.Runtime.CodeFluentEntityState ladderState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            if ((ladder != null))
            {
                ladderState = ladder.EntityState;
            }
            this._challengesLadderLadder = ladder;
            this._unspecifiedChallengeStatusStatus = null;
            this._unspecifiedFacilityFacility = null;
            this._unspecifiedCourtCourt = null;
            this._unspecifiedMatchFormatMatchFormat = null;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    Ladders.Challenge challenge = new Ladders.Challenge();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(challenge)).ReadRecord(reader);
                    if ((this.BaseContains(challenge) == false))
                    {
                        this.BaseAdd(challenge);
                        count = (count + 1);
                    }
                    challenge.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
            if ((ladder != null))
            {
                ladder.EntityState = ladderState;
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Ladders.ChallengeCollection PageLoadByLadder(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, Ladders.Ladder ladder)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            Ladders.ChallengeCollection ret = new Ladders.ChallengeCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = Ladders.ChallengeCollection.PageDataLoadByLadder(pageOptions, ladder);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadByLadder(pageIndex, pageSize, pageOptions, reader, ladder);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(TennisClubLadder.Constants.TennisClubLadderStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Ladders.ChallengeCollection LoadByLadder(Ladders.Ladder ladder)
        {
            Ladders.ChallengeCollection ret = Ladders.ChallengeCollection.PageLoadByLadder(int.MinValue, int.MaxValue, null, ladder);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadByLadder(CodeFluent.Runtime.PageOptions pageOptions, Ladders.Ladder ladder)
        {
            if ((ladder == null))
            {
                return null;
            }
            if ((ladder.Id == -1))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "ladder", "Ladders.Ladder");
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Challenge", "LoadByLadder");
            persistence.AddParameter("@LadderId", ladder.Id, ((int)(-1)));
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadByLadder(Ladders.Ladder ladder)
        {
            System.Data.IDataReader reader = Ladders.ChallengeCollection.PageDataLoadByLadder(null, ladder);
            return reader;
        }
        
        private void LoadByStatus(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader, Ladders.ChallengeStatus status)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            CodeFluent.Runtime.CodeFluentEntityState challengeStatusState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            if ((status != null))
            {
                challengeStatusState = status.EntityState;
            }
            this._challengesLadderLadder = null;
            this._unspecifiedChallengeStatusStatus = status;
            this._unspecifiedFacilityFacility = null;
            this._unspecifiedCourtCourt = null;
            this._unspecifiedMatchFormatMatchFormat = null;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    Ladders.Challenge challenge = new Ladders.Challenge();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(challenge)).ReadRecord(reader);
                    if ((this.BaseContains(challenge) == false))
                    {
                        this.BaseAdd(challenge);
                        count = (count + 1);
                    }
                    challenge.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
            if ((status != null))
            {
                status.EntityState = challengeStatusState;
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Ladders.ChallengeCollection PageLoadByStatus(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, Ladders.ChallengeStatus status)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            Ladders.ChallengeCollection ret = new Ladders.ChallengeCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = Ladders.ChallengeCollection.PageDataLoadByStatus(pageOptions, status);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadByStatus(pageIndex, pageSize, pageOptions, reader, status);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(TennisClubLadder.Constants.TennisClubLadderStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Ladders.ChallengeCollection LoadByStatus(Ladders.ChallengeStatus status)
        {
            Ladders.ChallengeCollection ret = Ladders.ChallengeCollection.PageLoadByStatus(int.MinValue, int.MaxValue, null, status);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadByStatus(CodeFluent.Runtime.PageOptions pageOptions, Ladders.ChallengeStatus status)
        {
            if ((status == null))
            {
                return null;
            }
            if ((status.Id == -1))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "status", "Ladders.ChallengeStatus");
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Challenge", "LoadByStatus");
            persistence.AddParameter("@StatusId", status.Id, ((int)(-1)));
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadByStatus(Ladders.ChallengeStatus status)
        {
            System.Data.IDataReader reader = Ladders.ChallengeCollection.PageDataLoadByStatus(null, status);
            return reader;
        }
        
        private void LoadByFacility(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader, Clubs.Facility facility)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            CodeFluent.Runtime.CodeFluentEntityState facilityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            if ((facility != null))
            {
                facilityState = facility.EntityState;
            }
            this._challengesLadderLadder = null;
            this._unspecifiedChallengeStatusStatus = null;
            this._unspecifiedFacilityFacility = facility;
            this._unspecifiedCourtCourt = null;
            this._unspecifiedMatchFormatMatchFormat = null;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    Ladders.Challenge challenge = new Ladders.Challenge();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(challenge)).ReadRecord(reader);
                    if ((this.BaseContains(challenge) == false))
                    {
                        this.BaseAdd(challenge);
                        count = (count + 1);
                    }
                    challenge.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
            if ((facility != null))
            {
                facility.EntityState = facilityState;
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Ladders.ChallengeCollection PageLoadByFacility(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, Clubs.Facility facility)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            Ladders.ChallengeCollection ret = new Ladders.ChallengeCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = Ladders.ChallengeCollection.PageDataLoadByFacility(pageOptions, facility);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadByFacility(pageIndex, pageSize, pageOptions, reader, facility);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(TennisClubLadder.Constants.TennisClubLadderStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Ladders.ChallengeCollection LoadByFacility(Clubs.Facility facility)
        {
            Ladders.ChallengeCollection ret = Ladders.ChallengeCollection.PageLoadByFacility(int.MinValue, int.MaxValue, null, facility);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadByFacility(CodeFluent.Runtime.PageOptions pageOptions, Clubs.Facility facility)
        {
            if ((facility == null))
            {
                return null;
            }
            if ((facility.Id == -1))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "facility", "Clubs.Facility");
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Challenge", "LoadByFacility");
            persistence.AddParameter("@FacilityId", facility.Id, ((int)(-1)));
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadByFacility(Clubs.Facility facility)
        {
            System.Data.IDataReader reader = Ladders.ChallengeCollection.PageDataLoadByFacility(null, facility);
            return reader;
        }
        
        private void LoadByCourt(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader, Clubs.Court court)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            CodeFluent.Runtime.CodeFluentEntityState courtState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            if ((court != null))
            {
                courtState = court.EntityState;
            }
            this._challengesLadderLadder = null;
            this._unspecifiedChallengeStatusStatus = null;
            this._unspecifiedFacilityFacility = null;
            this._unspecifiedCourtCourt = court;
            this._unspecifiedMatchFormatMatchFormat = null;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    Ladders.Challenge challenge = new Ladders.Challenge();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(challenge)).ReadRecord(reader);
                    if ((this.BaseContains(challenge) == false))
                    {
                        this.BaseAdd(challenge);
                        count = (count + 1);
                    }
                    challenge.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
            if ((court != null))
            {
                court.EntityState = courtState;
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Ladders.ChallengeCollection PageLoadByCourt(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, Clubs.Court court)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            Ladders.ChallengeCollection ret = new Ladders.ChallengeCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = Ladders.ChallengeCollection.PageDataLoadByCourt(pageOptions, court);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadByCourt(pageIndex, pageSize, pageOptions, reader, court);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(TennisClubLadder.Constants.TennisClubLadderStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Ladders.ChallengeCollection LoadByCourt(Clubs.Court court)
        {
            Ladders.ChallengeCollection ret = Ladders.ChallengeCollection.PageLoadByCourt(int.MinValue, int.MaxValue, null, court);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadByCourt(CodeFluent.Runtime.PageOptions pageOptions, Clubs.Court court)
        {
            if ((court == null))
            {
                return null;
            }
            if ((court.Id == -1))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "court", "Clubs.Court");
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Challenge", "LoadByCourt");
            persistence.AddParameter("@CourtId", court.Id, ((int)(-1)));
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadByCourt(Clubs.Court court)
        {
            System.Data.IDataReader reader = Ladders.ChallengeCollection.PageDataLoadByCourt(null, court);
            return reader;
        }
        
        private void LoadByMatchFormat(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader, Ladders.MatchFormat matchFormat)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            CodeFluent.Runtime.CodeFluentEntityState matchFormatState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            if ((matchFormat != null))
            {
                matchFormatState = matchFormat.EntityState;
            }
            this._challengesLadderLadder = null;
            this._unspecifiedChallengeStatusStatus = null;
            this._unspecifiedFacilityFacility = null;
            this._unspecifiedCourtCourt = null;
            this._unspecifiedMatchFormatMatchFormat = matchFormat;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    Ladders.Challenge challenge = new Ladders.Challenge();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(challenge)).ReadRecord(reader);
                    if ((this.BaseContains(challenge) == false))
                    {
                        this.BaseAdd(challenge);
                        count = (count + 1);
                    }
                    challenge.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
            if ((matchFormat != null))
            {
                matchFormat.EntityState = matchFormatState;
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Ladders.ChallengeCollection PageLoadByMatchFormat(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, Ladders.MatchFormat matchFormat)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            Ladders.ChallengeCollection ret = new Ladders.ChallengeCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = Ladders.ChallengeCollection.PageDataLoadByMatchFormat(pageOptions, matchFormat);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadByMatchFormat(pageIndex, pageSize, pageOptions, reader, matchFormat);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(TennisClubLadder.Constants.TennisClubLadderStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Ladders.ChallengeCollection LoadByMatchFormat(Ladders.MatchFormat matchFormat)
        {
            Ladders.ChallengeCollection ret = Ladders.ChallengeCollection.PageLoadByMatchFormat(int.MinValue, int.MaxValue, null, matchFormat);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadByMatchFormat(CodeFluent.Runtime.PageOptions pageOptions, Ladders.MatchFormat matchFormat)
        {
            if ((matchFormat == null))
            {
                return null;
            }
            if ((matchFormat.Id == -1))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "matchFormat", "Ladders.MatchFormat");
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Challenge", "LoadByMatchFormat");
            persistence.AddParameter("@MatchFormatId", matchFormat.Id, ((int)(-1)));
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(TennisClubLadder.Constants.TennisClubLadderStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadByMatchFormat(Ladders.MatchFormat matchFormat)
        {
            System.Data.IDataReader reader = Ladders.ChallengeCollection.PageDataLoadByMatchFormat(null, matchFormat);
            return reader;
        }
        
        protected virtual void BaseTrace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            writer.Write("[");
            writer.Write(string.Concat("Count=", this.Count));
            writer.Write("]");
        }
        
        public string Trace()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            System.IO.StringWriter stringWriter = new System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture);
            System.CodeDom.Compiler.IndentedTextWriter writer = new System.CodeDom.Compiler.IndentedTextWriter(stringWriter);
            this.BaseTrace(writer);
            writer.Flush();
            ((System.IDisposable)(writer)).Dispose();
            ((System.IDisposable)(stringWriter)).Dispose();
            string sr = stringBuilder.ToString();
            return sr;
        }
        
        void CodeFluent.Runtime.ICodeFluentObject.Trace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            this.BaseTrace(writer);
        }
        
        public virtual void CopyTo(Ladders.ChallengeCollection collection, bool deep)
        {
            if ((typeof(System.ICloneable).IsAssignableFrom(typeof(Ladders.Challenge)) == false))
            {
                deep = false;
            }
            System.Collections.Generic.IEnumerator<Ladders.Challenge> enumerator = this.GetEnumerator();
            bool b;
            for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
            {
                if ((deep == true))
                {
                    collection.Add(((Ladders.Challenge)(((System.ICloneable)(enumerator.Current)).Clone())));
                }
                else
                {
                    collection.Add(enumerator.Current);
                }
            }
        }
        
        public virtual Ladders.ChallengeCollection Clone(bool deep)
        {
            Ladders.ChallengeCollection ret = new Ladders.ChallengeCollection();
            this.CopyTo(ret, deep);
            return ret;
        }
        
        object System.ICloneable.Clone()
        {
            return this.Clone(true);
        }
        
        public virtual void CancelNew(int index)
        {
            if (((this._addNewPos >= 0) 
                        && (this._addNewPos == index)))
            {
                this.RemoveAt(index);
                this._addNewPos = -1;
            }
        }
        
        public virtual void EndNew(int index)
        {
            if (((this._addNewPos >= 0) 
                        && (this._addNewPos == index)))
            {
                this._addNewPos = -1;
            }
        }
        
        void System.ComponentModel.IBindingList.AddIndex(System.ComponentModel.PropertyDescriptor property)
        {
            this._blm2279252929.AddIndex(property);
        }
        
        protected virtual void OnAddingNew(System.ComponentModel.AddingNewEventArgs e)
        {
            if ((this.AddingNew != null))
            {
                this.AddingNew(this, e);
            }
        }
        
        object System.ComponentModel.IBindingList.AddNew()
        {
            Ladders.Challenge add = new Ladders.Challenge();
            System.ComponentModel.AddingNewEventArgs e = new System.ComponentModel.AddingNewEventArgs(add);
            this.OnAddingNew(e);
            add = ((Ladders.Challenge)(e.NewObject));
            if ((add == null))
            {
                add = new Ladders.Challenge();
            }
            add.Id = 0;
            this._addNewPos = this.Add(add);
            return add;
        }
        
        void System.ComponentModel.IBindingList.ApplySort(System.ComponentModel.PropertyDescriptor property, System.ComponentModel.ListSortDirection direction)
        {
            this._blm2279252929.ApplySort(property, direction);
        }
        
        int System.ComponentModel.IBindingList.Find(System.ComponentModel.PropertyDescriptor property, object key)
        {
            return this._blm2279252929.Find(property, key);
        }
        
        void System.ComponentModel.IBindingList.RemoveIndex(System.ComponentModel.PropertyDescriptor property)
        {
            this._blm2279252929.RemoveIndex(property);
        }
        
        void System.ComponentModel.IBindingList.RemoveSort()
        {
            this._blm2279252929.RemoveSort();
        }
        
        protected virtual void OnListChanged(System.ComponentModel.ListChangedEventArgs e)
        {
            if ((e == null))
            {
                throw new System.ArgumentNullException("e");
            }
            if ((this.RaiseListChangedEvents == false))
            {
                return;
            }
            if ((((e.ListChangedType == System.ComponentModel.ListChangedType.Reset) 
                        == false) 
                        && (e.NewIndex < 0)))
            {
                return;
            }
            if ((this.ListChanged != null))
            {
                this.ListChanged(this, e);
            }
        }
        
        public void AddRange(System.Collections.Generic.IEnumerable<Ladders.Challenge> collection)
        {
            CodeFluent.Runtime.Utilities.ConvertUtilities.AddRange(this, collection);
        }
        
        private void OnItemKeyChanged(object sender, CodeFluent.Runtime.Utilities.KeyChangedEventArgs<int> e)
        {
            if ((e == null))
            {
                throw new System.ArgumentNullException("e");
            }
            Ladders.Challenge existing;
            if ((this.BaseTable.TryGetValue(e.OldKey, out existing) == false))
            {
                return;
            }
            if (((sender != null) 
                        && (typeof(CodeFluent.Runtime.Utilities.IKeyable<int>).IsAssignableFrom(sender.GetType()) == true)))
            {
                CodeFluent.Runtime.Utilities.IKeyable<int> item = ((CodeFluent.Runtime.Utilities.IKeyable<int>)(sender));
                try
                {
                    this.BaseTable.Add(item.Key, existing);
                }
                catch (System.ArgumentNullException ane)
                {
                    throw new System.ArgumentNullException(TennisClubLadder.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "Ladders.ChallengeCollection", ((CodeFluent.Runtime.ICodeFluentEntity)(item)).EntityKey), ane);
                }
                catch (System.ArgumentException ae)
                {
                    throw new System.ArgumentException(TennisClubLadder.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "Ladders.ChallengeCollection", item.Key), ae);
                }
                this.BaseTable.Remove(e.OldKey);
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Ladders.ChallengeCollection PageLoadAll(int pageIndex, int pageSize)
        {
            return Ladders.ChallengeCollection.PageLoadAll(pageIndex, pageSize, null);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Ladders.ChallengeCollection PageLoadByLadder(int pageIndex, int pageSize, int ladderId)
        {
            Ladders.Ladder ladder = Ladders.Ladder.Load(ladderId);
            if ((ladder == null))
            {
                return new Ladders.ChallengeCollection();
            }
            return Ladders.ChallengeCollection.PageLoadByLadder(pageIndex, pageSize, null, ladder);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Ladders.ChallengeCollection PageLoadByStatus(int pageIndex, int pageSize, int statusId)
        {
            Ladders.ChallengeStatus challengeStatus = Ladders.ChallengeStatus.Load(statusId);
            if ((challengeStatus == null))
            {
                return new Ladders.ChallengeCollection();
            }
            return Ladders.ChallengeCollection.PageLoadByStatus(pageIndex, pageSize, null, challengeStatus);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Ladders.ChallengeCollection PageLoadByFacility(int pageIndex, int pageSize, int facilityId)
        {
            Clubs.Facility facility = Clubs.Facility.Load(facilityId);
            if ((facility == null))
            {
                return new Ladders.ChallengeCollection();
            }
            return Ladders.ChallengeCollection.PageLoadByFacility(pageIndex, pageSize, null, facility);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Ladders.ChallengeCollection PageLoadByCourt(int pageIndex, int pageSize, int courtId)
        {
            Clubs.Court court = Clubs.Court.Load(courtId);
            if ((court == null))
            {
                return new Ladders.ChallengeCollection();
            }
            return Ladders.ChallengeCollection.PageLoadByCourt(pageIndex, pageSize, null, court);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Ladders.ChallengeCollection PageLoadByMatchFormat(int pageIndex, int pageSize, int matchFormatId)
        {
            Ladders.MatchFormat matchFormat = Ladders.MatchFormat.Load(matchFormatId);
            if ((matchFormat == null))
            {
                return new Ladders.ChallengeCollection();
            }
            return Ladders.ChallengeCollection.PageLoadByMatchFormat(pageIndex, pageSize, null, matchFormat);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)]
        public static bool Save(Ladders.Challenge challenge)
        {
            if ((challenge == null))
            {
                return false;
            }
            bool ret = challenge.Save();
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)]
        public static bool Insert(Ladders.Challenge challenge)
        {
            bool ret = Ladders.Challenge.Save(challenge);
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)]
        public static bool Delete(Ladders.Challenge challenge)
        {
            if ((challenge == null))
            {
                return false;
            }
            bool ret = challenge.Delete();
            return ret;
        }
    }
}
